version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building application...
      - npm run build

  post_build:
    commands:
      - echo Uploading files to S3...
      - aws s3 sync dist/ $bucket_name  --delete

      - echo Creating CloudFront invalidation...
      - aws cloudfront create-invalidation --distribution-id $distribuition_id --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: dist